## Ran Uram 206661886 
## Shahar Lankry 322659137 
## Daniel Geron 212515522
-------------------------

## Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')
import cv2
import numpy as np
import os
from pathlib import Path
import argparse
import pandas as pd
import re
from typing import Tuple
from tqdm import tqdm
from openpyxl import load_workbook

## Change paths to match your folders location

In [2]:
og_images_folder=r"C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/Data"
normalised_images_folder=r"C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/Data_normalized"
feature_tables_location=r"C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables"

#creating folders for results
visualization_folder=r"C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/visualization_results"
if not os.path.exists(visualization_folder):
    os.makedirs(visualization_folder)
for feature in ['baseline','slant','stroke_thickness','right_margin','left_margin','word_aspect_ratio','baseline_slope']:
    feature_folder=os.path.join(visualization_folder,feature)
    if not os.path.exists(feature_folder):
        os.makedirs(feature_folder)

## Image normalization

In [3]:
def binarize_image(img: np.ndarray, method: str = 'sauvola') -> np.ndarray:
    # Converts grayscale image to binary (black and white) using thresholding.
    # This separates the ink (text) from the paper (background).

    if method == 'otsu':
        # Otsu finds a single global threshold for the whole image (good for uniform lighting)
        _, binary = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    elif method == 'adaptive':
        # Adaptive calculates threshold locally for small regions (better for shadows/uneven lighting)
        binary = cv2.adaptiveThreshold(
            img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY, 21, 10
        )

    elif method == 'sauvola':
        # Sauvola is a specific adaptive method optimized for documents.
        # Here we use a tuned Adaptive Threshold as a robust fallback implementation.
        binary = cv2.adaptiveThreshold(
            img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY, 25, 15
        )

    else:
        raise ValueError(f"Unknown binarization method: {method}")

    return binary

In [4]:
def remove_noise(binary_img: np.ndarray, min_component_size: int = 10) -> np.ndarray:
    # Cleans the image by removing small specks and dots that aren't part of the text.
    
    # Morphological Opening: Erodes then Dilates to remove tiny noise (salt-and-pepper noise)
    kernel = np.ones((2, 2), np.uint8)
    opened = cv2.morphologyEx(binary_img, cv2.MORPH_OPEN, kernel, iterations=1)

    # Connected Components: Identifies all separated blobs in the image
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(255 - opened, connectivity=8)
    # Create a clean black canvas
    output = np.zeros_like(opened)

    # Copy only the components that are large enough (actual letters) to the new image
    for i in range(1, num_labels):
        area = stats[i, cv2.CC_STAT_AREA]
        if area >= min_component_size:
            output[labels == i] = 255

    # Invert back to ensure text is black on white background
    output = 255 - output

    return output

In [5]:
def crop_to_content(img: np.ndarray, padding: int = 20) -> np.ndarray:
    # Cuts away the empty white margins, keeping only the area with actual handwriting.
    
    # Find coordinates of all black pixels (text)
    coords = cv2.findNonZero(255 - img)

    if coords is None:
        return img

    # Get the bounding box (rectangle) that surrounds all the text
    x, y, w, h = cv2.boundingRect(coords)

    # Add some padding (white space) around the text so it doesn't touch the edges
    x = max(0, x - padding)
    y = max(0, y - padding)
    w = min(img.shape[1] - x, w + 2 * padding)
    h = min(img.shape[0] - y, h + 2 * padding)

    # Perform the actual crop
    cropped = img[y:y+h, x:x+w]

    return cropped

In [6]:
def normalize_height(img: np.ndarray, target_height: int = 64) -> np.ndarray:
    # Resizes the image to a fixed height (e.g., 64px) while keeping the Aspect Ratio.
    # This ensures the letters don't get squashed or stretched unnaturally.
    
    h, w = img.shape[:2]

    # Calculate new width based on aspect ratio
    aspect_ratio = w / h
    new_width = int(target_height * aspect_ratio)
    
    # Resize using INTER_AREA interpolation (best for shrinking images)
    resized = cv2.resize(img, (new_width, target_height), interpolation=cv2.INTER_AREA)

    return resized

In [7]:
def process_single_image(
    input_path: str, output_path: str, binarize: bool = True,
    denoise: bool = True, crop: bool = True, normalize_size: bool = False,
    target_height: int = 64, binarization_method: str = 'adaptive', min_noise_size: int = 10
) -> bool:
    # The main pipeline for a single file. Runs all steps in order.
    
    try:
        img = cv2.imread(input_path)
        if img is None:
            return False

        # Convert to grayscale first
        if len(img.shape) == 3:
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        else:
            gray = img

        processed = gray.copy()

        # Step 1: Binarization (Thresholding)
        if binarize:
            processed = binarize_image(processed, method=binarization_method)

        # Step 2: Noise Removal (Cleaning)
        if denoise:
            processed = remove_noise(processed, min_component_size=min_noise_size)

        # Step 3: Smart Cropping
        if crop:
            processed = crop_to_content(processed, padding=20)

        # Step 4: Height Normalization (Optional)
        if normalize_size and target_height > 0:
            processed = normalize_height(processed, target_height=target_height)

        # Save the final processed image
        cv2.imwrite(output_path, processed)

        return True

    except Exception as e:
        print(f"Error: {e}")
        return False

In [8]:
def process_directory(input_dir: str, output_dir: str, **kwargs) -> None:
    # Iterates over the entire folder and processes every image found.
    
    os.makedirs(output_dir, exist_ok=True)

    image_files = []
    # Find all image files with common extensions
    for ext in ['.png', '.jpg', '.jpeg', '.tif', '.tiff']:
        image_files.extend(Path(input_dir).glob(f'*{ext}'))
        image_files.extend(Path(input_dir).glob(f'*{ext.upper()}'))

    # Sort and remove duplicates
    image_files = sorted(list(set(image_files)))
    total = len(image_files)

    print(f"Found {total} images to process")
    print(f"Output directory: {output_dir}")
    print("-" * 60)

    success_count = 0

    # Loop through all images
    for idx, img_path in enumerate(image_files, 1):
        output_path = os.path.join(output_dir, img_path.name)

        # Process the current image
        success = process_single_image(str(img_path), output_path, **kwargs)

        if success:
            success_count += 1
            if idx % 100 == 0:
                print(f"Processed {idx}/{total} images...")
        else:
            print(f"[ERROR] Failed to process {img_path.name}")

    print("-" * 60)
    print(f"Done! Successfully processed: {success_count}/{total}")

In [9]:

    # 3. Processing Settings (Change to False if you want to skip a step)
should_binarize = True
should_denoise = True
should_crop = True
should_normalize_height = False
    

    # Check if input directory exists before starting
if 'og_images_folder' not in locals():
    print("Error: Variables not defined. Please run the cell with the paths first (Cell 2).")
elif not os.path.exists(og_images_folder):
    print(f"Error: The input folder does not exist at:\n{og_images_folder}")
else:
    print(f"Folder found! Processing images...")

    # Run the processing
    process_directory(
            input_dir=og_images_folder,
            output_dir=normalised_images_folder,
            binarize=should_binarize,
            denoise=should_denoise,
            crop=should_crop,
            normalize_size=should_normalize_height,
            target_height=64 
    )

Folder found! Processing images...
Found 2512 images to process
Output directory: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/Data_normalized
------------------------------------------------------------
Processed 100/2512 images...
Processed 200/2512 images...
Processed 300/2512 images...
Processed 400/2512 images...
Processed 500/2512 images...
Processed 600/2512 images...
Processed 700/2512 images...
Processed 800/2512 images...
Processed 900/2512 images...
Processed 1000/2512 images...
Processed 1100/2512 images...
Processed 1200/2512 images...
Processed 1300/2512 images...
Processed 1400/2512 images...
Processed 1500/2512 images...
Processed 1600/2512 images...
Processed 1700/2512 images...
Processed 1800/2512 images...
Processed 1900/2512 images...
Processed 2000/2512 images...
Processed 2100/2512 images...
Processed 2200/2512 images...
Processed 2300/2512 images...
Processed 2400/2512 images...
Processed 2500/2512 images...
------------------------------------------------------------
Done! Successfully processed: 2512/2512

## FEATURE EXTRACTION

<table dir="rtl" style="border-collapse: collapse; width: 100%; text-align: right; border: 1px solid black;">
    <thead>
        <tr>
            <th style="border: 1px solid black; padding: 10px;">ערכי הקיצון והאמצע (סקאלה 0-1)</th>
            <th style="border: 1px solid black; padding: 10px;">מה זה אומר? (תיאור)</th>
            <th style="border: 1px solid black; padding: 10px;">שם הפיצ'ר</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = שמאלית חזקה (נגד הכיוון)<br>0.5 = אנכי לגמרי (90 מעלות, ישר)<br>1.0 = ימנית חזקה (שוכב קדימה)</td>
            <td style="border: 1px solid black; padding: 10px;">זווית הכתיבה ביחס לאנך</td>
            <td style="border: 1px solid black; padding: 10px;">נטייה (Slant)</td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = דקיק (קו נימי, עדין מאוד)<br>0.5 = בינוני (עובי סטנדרטי)<br>1.0 = עבה מאוד (קו "בצקי", מרוח)</td>
            <td style="border: 1px solid black; padding: 10px;">עובי הקו ביחס לגודל האות ("לחץ")</td>
            <td style="border: 1px solid black; padding: 10px;">עובי קו (Stroke Thickness)</td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = חותך/יורד (הכתיבה יורדת מתחת לקו)<br>0.5 = על הקו בדיוק (התאמה מושלמת)<br>1.0 = מרחף גבוה (הכתיבה מנותקת מהקו כלפי מעלה)</td>
            <td style="border: 1px solid black; padding: 10px;">מיקום האות ביחס לפס המודפס</td>
            <td style="border: 1px solid black; padding: 10px;">היצמדות לשורה (Baseline)</td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = צמוד לקצה הימני (0% עד 5% מרוחב הדף)<br>0.5 = מרחק מאוזן מהקצה (10% עד 15%)<br>1.0 = מרחק גדול מהקצה הימני (מעל 30%)</td>
            <td style="border: 1px solid black; padding: 10px;">המרחק מהפיקסל השחור הראשון בשורה לקצה הימני של המסגרת</td>
            <td style="border: 1px solid black; padding: 10px;"><strong>מדידת שוליים- ימין (Margin Right)</strong></td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = צמוד לקצה השמאלי (0% עד 5% מרוחב הדף)<br>0.5 = מרחק מאוזן מהקצה (10% עד 15%)<br>1.0 = מרחק גדול מהקצה השמאלי (מעל 30%)</td>
            <td style="border: 1px solid black; padding: 10px;">המרחק מהפיקסל האחרון לקצה השמאלי של המסגרת</td>
            <td style="border: 1px solid black; padding: 10px;"><strong>מדידת שוליים- שמאל (Margin Left)</strong></td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">-1 = זוהתה מילה אחת בלבד (לא ניתן למדוד)<br>0.0 = מילים דבוקות (אין רווח)<br>0.5 = רווח תקין בין מילים<br>1.0 = רווחים גדולים מאוד בין מילים</td>
            <td style="border: 1px solid black; padding: 10px;">המרחק החציוני בין מילים שזוהו בשורה</td>
            <td style="border: 1px solid black; padding: 10px;"><strong>רווח בין מילים (Word Spacing)</strong></td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = כתב זעיר- תופס שטח מינימלי מהשורה<br>0.5 = כתב בינוני ותקני- פרופורציה הגיונית<br>1.0 = כתב ענק- משתלט על מרחב השורה</td>
            <td style="border: 1px solid black; padding: 10px;">המרחק האנכי של האותיות, מחושב כחציון גובה התיבות התוחמות ומנורמל לגובה הדף</td>
            <td style="border: 1px solid black; padding: 10px;"><strong>גודל הכתב האבסולוטי (Letter Size)</strong></td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = כתב זוויתי- קווים חדים ושפיצים<br>0.5 = שילוב מאוזן- עקומות מתונות וזורמות<br>1.0 = כתב עגול- צורות עגולות, רכות ומלאות</td>
            <td style="border: 1px solid black; padding: 10px;">בדיקת ה"שפיציות" של הכתב דרך חישוב מדד המעגליות של החללים הלבנים בתוך האותיות</td>
            <td style="border: 1px solid black; padding: 10px;">מעגליות מול זוויתיות (Roundness vs. Angularity)</td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = שורה נופלת (שיפוע רגרסיה חיובי)<br>0.5 = שורה ישרה (קו אופקי ושטוח)<br>1.0 = שורה מטפסת (שיפוע רגרסיה שלילי)</td>
            <td style="border: 1px solid black; padding: 10px;">כיוון הזרימה של השורה, מחושב באמצעות רגרסיה לינארית על מרכזי הכובד של המילים</td>
            <td style="border: 1px solid black; padding: 10px;">שיפוע קו הבסיס (Baseline Slope)</td>
        </tr>
        <tr>
            <td style="border: 1px solid black; padding: 10px;">0.0 = מילים צרות ומכווצות- דחוסות כלפי פנים<br>0.5 = פרופורציה מאוזנת- יחס רוחב-גובה תקין<br>1.0 = מילים רחבות ומתוחות- מרוחות על הדף</td>
            <td style="border: 1px solid black; padding: 10px;">בדיקת "מתיחת" המילה בחלל, מחושב כחציון היחס בין רוחב התיבה התוחמת לגובהה</td>
            <td style="border: 1px solid black; padding: 10px;">יחס רוחב-גובה של המילים (Word Aspect Ratio)</td>
        </tr>
    </tbody>
</table>

### Slant

In [10]:
def measure_slant_by_shear(binary_img: np.ndarray) -> Tuple[float, float]:
    # Calculates the slant by applying affine shear transformations to the image.
    # Logic: We shear the image at different angles. The angle that maximizes the 
    # variance of the vertical projection is the one that makes the text most upright.
    
    img_height, img_width = binary_img.shape
    
    # Test angles from -30 to +30 degrees
    angles_to_test = np.linspace(-30, 30, 61)
    max_variance = 0
    optimal_angle = 0

    for angle in angles_to_test:
        angle_rad = np.radians(angle)
        shear_factor = np.tan(angle_rad)
        
        # Define the Affine Transformation Matrix for shearing
        M = np.array([[1, shear_factor, 0],
                      [0, 1, 0]], dtype=np.float32)
        
        # Apply the shear transformation
        sheared = cv2.warpAffine(binary_img, M, (img_width + abs(int(shear_factor * img_height)), img_height),
                                flags=cv2.INTER_LINEAR, borderValue=255)
        
        # Calculate vertical projection (sum of black pixels per column)
        projection = np.sum(sheared == 0, axis=0)
        
        # Calculate variance - higher variance means sharper peaks/valleys, indicating upright text
        variance = np.var(projection)

        if variance > max_variance:
            max_variance = variance
            optimal_angle = angle

    # Normalize the result to 0.0 - 1.0 range
    # -30 deg = 0.0, 0 deg = 0.5, +30 deg = 1.0
    slant = (optimal_angle + 30) / 60
    slant = np.clip(slant, 0.0, 1.0)
    
    return slant, optimal_angle

In [11]:
def measure_slant_by_moments(binary_img: np.ndarray) -> float:
    # Calculates slant by finding contours of individual letters and fitting ellipses.
    # The average angle of these ellipses represents the handwriting slant.
    
    # Invert image to find contours (OpenCV expects white object on black background)
    inverted = 255 - binary_img
    contours, _ = cv2.findContours(inverted, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return 0.5

    angles = []
    img_area = binary_img.shape[0] * binary_img.shape[1]

    for contour in contours:
        area = cv2.contourArea(contour)
        
        # Filter noise: Ignore contours that are too small or too large
        if area < img_area * 0.0001 or area > img_area * 0.15:
            continue
        if len(contour) < 5:
            continue

        try:
            # Fit an ellipse to the contour to determine orientation
            (x, y), (MA, ma), angle = cv2.fitEllipse(contour)
            
            # Adjust angle to be relative to vertical axis
            if angle > 135:
                angle = angle - 180
            elif angle > 45:
                angle = 90 - angle
            angles.append(angle)
        except:
            continue

    if not angles:
        return 0.5

    # Remove statistical outliers using Interquartile Range (IQR) to get a robust mean
    angles = np.array(angles)
    q1, q3 = np.percentile(angles, [25, 75])
    iqr = q3 - q1
    if iqr > 0:
        mask = (angles >= q1 - 1.5*iqr) & (angles <= q3 + 1.5*iqr)
        angles = angles[mask]

    if len(angles) == 0:
        return 0.5

    mean_angle = np.mean(angles)
    
    # Normalize to 0.0 - 1.0 range based on -20 to +20 degrees limits
    mean_angle = np.clip(mean_angle, -20, 20)
    slant = (mean_angle + 20) / 40
    return slant

In [12]:
def extract_slant(image_path: str) -> Tuple[float, dict]:
    # Main function to process a single image.
    # Combines Shear method (global) and Moments method (local) for better accuracy.
    
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return 0.5, {'error': 'Failed to read'}

    # Ensure binary image (Thresholding) if not already
    if len(np.unique(img)) > 2:
        _, img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

    # Run both algorithms
    slant_shear, optimal_angle = measure_slant_by_shear(img)
    slant_moments = measure_slant_by_moments(img)

    # Weighted Average: Giving more weight (0.7) to the Shear method as it is generally more robust for lines
    slant = 0.7 * slant_shear + 0.3 * slant_moments
    slant = np.clip(slant, 0.0, 1.0)
    debug_info = {
        'slant_shear': slant_shear,
        'slant_moments': slant_moments,
        'optimal_angle': optimal_angle
    }
    return slant, debug_info

In [13]:
def process_directory(input_dir: str, output_file: str) -> pd.DataFrame:
    # Iterates over all images in the directory, calculates slant, and saves to Excel.
    
    image_files = []
    # Collect all common image formats
    for ext in ['.png', '.jpg', '.jpeg', '.tif', '.tiff']:
        image_files.extend(Path(input_dir).glob(f'*{ext}'))
        image_files.extend(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(set(image_files))
    total = len(image_files)

    print(f"Found {total} images")
    print(f"Output: {output_file}")
    
    results = []
    # Process images with a progress bar
    for idx, img_path in enumerate(tqdm(image_files, desc="Processing"), 1):
        slant, debug = extract_slant(str(img_path))
        results.append({
            'Image Number': idx,
            'File Name': img_path.name,
            'Slant': round(slant, 3)
        })
        img_copy=cv2.imread(str(img_path))
        cv2.rectangle(img_copy,(5,5),(200,50),(0,0,0),-1)
        cv2.putText(img_copy, f"Slant: {slant:.3f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
        cv2.imwrite(os.path.join(visualization_folder,'slant',img_path.name),img_copy)

    # Save initial data to Excel
    df = pd.DataFrame(results)
    df.to_excel(output_file, index=False, engine='openpyxl')

    # Post-processing: Add Excel formula to extract image index from filename if needed
    wb = load_workbook(output_file)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
    wb.save(output_file)

    print(f"\nStatistics:")
    print(f"  Mean: {df['Slant'].mean():.3f}")
    print(f"  Median: {df['Slant'].median():.3f}")
    print(f"  Std Dev: {df['Slant'].std():.3f}")
    print(f"  Min: {df['Slant'].min():.3f}")
    print(f"  Max: {df['Slant'].max():.3f}")
    return df

In [14]:
process_directory(normalised_images_folder,os.path.join(feature_tables_location, 'slant.xlsx'))

Found 2512 images
Output: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\slant.xlsx

Processing: 100%|██████████| 2512/2512 [01:42<00:00, 24.39it/s]

Statistics:
  Mean: 0.535
  Median: 0.520
  Std Dev: 0.130
  Min: 0.015
  Max: 1.000

      Image Number       File Name  Slant
0                1     txt (1).png  0.433
1                2    txt (10).png  0.589
2                3   txt (100).png  0.585
3                4  txt (1000).png  0.611
4                5  txt (1001).png  0.439
...            ...             ...    ...
2507          2508   txt (995).png  0.466
2508          2509   txt (996).png  0.483
2509          2510   txt (997).png  0.611
2510          2511   txt (998).png  0.633
2511          2512   txt (999).png  0.499

[2512 rows x 3 columns]

### Stroke Thickness

In [15]:
def remove_printed_text_and_lines(img: np.ndarray) -> np.ndarray:
    # Preprocesses image to remove horizontal ruled lines and noise, isolating handwriting
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img

    # Create binary inverse (white text on black background)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)
    height, width = img.shape[:2]

    # Detect and remove horizontal lines using Hough Transform
    lines_mask = np.zeros_like(binary)
    lines = cv2.HoughLinesP(binary, 1, np.pi/180, threshold=100, minLineLength=width*0.3, maxLineGap=10)
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            # Draw thick lines over detected ruled lines to mask them
            cv2.line(lines_mask, (x1, y1), (x2, y2), 255, 8)

    # Subtract lines from the binary image
    binary_no_lines = cv2.bitwise_and(binary, cv2.bitwise_not(lines_mask))
    
    # Filter out noise and irrelevant regions using Connected Components
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(binary_no_lines, connectivity=8)
    handwriting_mask = np.zeros_like(binary_no_lines)

    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        # Define regions to ignore (header, footer) and noise threshold
        is_bottom_region = (y + h) > height * 0.85
        is_top_region = y < height * 0.1
        is_too_small = area < 15

        # Keep only valid handwriting components
        if not (is_bottom_region or is_top_region or is_too_small):
            handwriting_mask[labels == i] = 255

    # Invert back to normal (black text on white background)
    result = cv2.bitwise_not(handwriting_mask)
    return result

In [16]:
def calculate_stroke_thickness_pure(img: np.ndarray) -> float:
    # Calculates average stroke thickness using Distance Transform
    handwriting_only = remove_printed_text_and_lines(img)

    if len(handwriting_only.shape) == 3:
        gray = cv2.cvtColor(handwriting_only, cv2.COLOR_BGR2GRAY)
    else:
        gray = handwriting_only

    # Binary thresholding
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    inverted = cv2.bitwise_not(binary)

    # Distance Transform: calculates distance of each pixel to the nearest zero pixel (background)
    # This effectively measures the "skeleton" width at every point
    dist_transform = cv2.distanceTransform(inverted, cv2.DIST_L2, 5)
    text_distances = dist_transform[dist_transform > 0]

    # Calculate ratio of handwriting pixels to total area
    total_pixels = inverted.shape[0] * inverted.shape[1]
    handwriting_ratio = len(text_distances) / total_pixels if total_pixels > 0 else 0

    # Safety check: If page is empty or has too little content, try raw image or return 0
    MINIMUM_CONTENT_THRESHOLD = 0.003 
    if len(text_distances) == 0 or handwriting_ratio < MINIMUM_CONTENT_THRESHOLD:
        if len(img.shape) == 3:
            gray_raw = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        else:
            gray_raw = img

        _, binary_raw = cv2.threshold(gray_raw, 127, 255, cv2.THRESH_BINARY)
        inverted_raw = cv2.bitwise_not(binary_raw)

        dist_transform_raw = cv2.distanceTransform(inverted_raw, cv2.DIST_L2, 5)
        text_distances = dist_transform_raw[dist_transform_raw > 0]

        if len(text_distances) == 0:
            return 0.0
    
    # Mean distance is the radius, so multiply by 2 for diameter (thickness)
    avg_thickness = np.mean(text_distances) * 2

    return avg_thickness

In [17]:
def process_images_for_stroke_thickness(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main processing loop: iterates images, calculates raw thickness, and normalizes results

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files))
    total = len(image_files)

    print(f"Found {total} images to analyze")
    print(f"Output Excel file: {output_excel}")
    
    raw_thickness_values = []
    temp_results = []

    # Step 1: Calculate raw thickness for all images
    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)

            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({
                    'Image_Number': idx,
                    'Filename': img_path.name,
                    'Raw_Thickness': None
                })
                continue

            stroke_thickness = calculate_stroke_thickness_pure(img)
            raw_thickness_values.append(stroke_thickness)

            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Thickness': stroke_thickness
            })
            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] Failed to process {img_path.name}: {str(e)}")
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Thickness': None
            })

    print(f"Analysis complete!")

    # Step 2: Normalize values to 0-1 range based on dataset min/max
    valid_values = [r for r in raw_thickness_values if r is not None and r > 0]
    min_thickness = min(valid_values) if valid_values else 0.0
    max_thickness = max(valid_values) if valid_values else 1.0
    thickness_range = max_thickness - min_thickness

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min: {min_thickness:.3f} pixels")
    print(f"Raw max: {max_thickness:.3f} pixels")

    results = []
    for item in temp_results:
        if item['Raw_Thickness'] is None:
            normalized_value = None
        elif item['Raw_Thickness'] == 0:
            normalized_value = 0.0
        elif thickness_range == 0:
            normalized_value = 0.5
        else:
            # Min-Max Normalization formula
            normalized_value = (item['Raw_Thickness'] - min_thickness) / thickness_range

        results.append({
            'Image_Number': item['Image_Number'],
            'Filename': item['Filename'],
            'Stroke_Thickness': round(normalized_value, 3)
        })
        #saving visualization of the results for better understanding
        path=os.path.join(normalised_images_folder,item['Filename'])
        img=cv2.imread(path)
        cv2.rectangle(img,(5,5),(310,50),(0,0,0),-1)
        cv2.putText(img,f"Stroke Thickness:{normalized_value:.3f}",(10,30),cv2.FONT_HERSHEY_SIMPLEX,0.8,(0,0,255),2)
        cv2.imwrite(os.path.join(visualization_folder,'stroke_thickness',item['Filename']),img)
    # Save to Excel
    df = pd.DataFrame(results)
    # Ensuring the results are rounded to 3 decimal
    df['Stroke_Thickness']=df['Stroke_Thickness'].astype(float).round(3)
    df.to_excel(output_excel, index=False, sheet_name='Stroke Thickness')

    wb=load_workbook(output_excel)
    ws=wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
    wb.save(output_excel)

    #save visualization of the results

    print(f"\nExcel file saved: {output_excel}")
    print("\nNormalized Stroke Thickness Statistics (0-1 range):")
    print(f"Min: {df['Stroke_Thickness'].min():.3f}")
    print(f"Max: {df['Stroke_Thickness'].max():.3f}")
    print(f"Mean: {df['Stroke_Thickness'].mean():.3f}")
    print(f"Median: {df['Stroke_Thickness'].median():.3f}")
    print(f"Std Dev: {df['Stroke_Thickness'].std():.3f}")

    return df

In [18]:
process_images_for_stroke_thickness(input_dir=normalised_images_folder, output_excel=os.path.join(feature_tables_location, 'stroke_thickness.xlsx'))

Found 2512 images to analyze
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\stroke_thickness.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min: 2.031 pixels
Raw max: 3.068 pixels

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\stroke_thickness.xlsx

Normalized Stroke Thickness Statistics (0-1 range):
Min: 0.000
Max: 1.000
Mean: 0.294
Median: 0.290
Std Dev: 0.109

      Image_Number        Filename  Stroke_Thickness
0                1     txt (1).png             0.368
1                2    txt (10).png             0.065
2                3   txt (100).png             0.348
3                4  txt (1000).png             0.487
4                5  txt (1001).png             0.301
...            ...             ...               ...
2507          2508   txt (995).png             0.394
2508          2509   txt (996).png             0.339
2509          2510   txt (997).png             0.191
2510          2511   txt (998).png             0.233
2511          2512   txt (999).png             0.323

[2512 rows x 3 columns]

### Baseline

In [19]:
def extract_file_id(filename: str) -> int:
    # Helper function to extract the first number from a filename for natural sorting
    match = re.search(r'(\d+)', filename)
    if match:
        return int(match.group(1))
    return -1

In [20]:
def calculate_position_score(img: np.ndarray) -> float:
    # core logic: Calculates vertical position relative to the baseline.
    # Returns a score between 0.0 (Cutting the line) and 1.0 (Floating above).
    copy_img=img.copy()
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img

    # Otsu's thresholding to create binary image
    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    img_h, img_w = thresh.shape

    # Define a wide horizontal kernel to detect only the ruled lines (ignoring text)
    min_line_width = int(img_w * 0.3)
    horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (min_line_width, 1))
    
    # Morphological opening to isolate horizontal lines
    detected_lines_map = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel, iterations=1)
    
    cnts_lines, _ = cv2.findContours(detected_lines_map, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    if not cnts_lines:
        return None,copy_img

    valid_lines = []
    for c in cnts_lines:
        x, y, w, h = cv2.boundingRect(c)
        # Filter out lines that are too close to the top/bottom borders (noise)
        if y > 10 and y < img_h - 10:
            valid_lines.append(c)
            
    if not valid_lines:
        valid_lines = [max(cnts_lines, key=cv2.contourArea)]

    # Subtract the detected lines from original binary to get only the handwriting
    text_only = cv2.subtract(thresh, detected_lines_map)
    
    # Clean small noise
    kernel_clean = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    text_only = cv2.morphologyEx(text_only, cv2.MORPH_OPEN, kernel_clean)
    
    cnts_text, _ = cv2.findContours(text_only, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    text_bottoms = []
    text_centers_y = []
    
    for c in cnts_text:
        if cv2.contourArea(c) < 15:
            continue
            
        tx, ty, tw, th = cv2.boundingRect(c)
        text_bottoms.append(ty + th)
        text_centers_y.append(ty + th/2)

    if not text_bottoms:
        return 1.0,copy_img

    # Use Median to determine text baseline position, ignoring outliers like descending letters ('ן', 'ך')
    median_text_bottom = np.median(text_bottoms)
    avg_text_y = np.mean(text_centers_y)

    best_line_y = 0
    min_dist_to_line = 99999
    
    # Identify which ruled line the text belongs to (closest line to text center)
    for line_c in valid_lines:
        lx, ly, lw, lh = cv2.boundingRect(line_c)
        current_line_y = ly 
        
        dist = abs(current_line_y - avg_text_y)
        if dist < min_dist_to_line:
            min_dist_to_line = dist
            best_line_y = current_line_y

    # Calculate distance: Positive = Above line, Negative = Below line
    distance = best_line_y - median_text_bottom
    
    # Sensitivity factor: determines the pixel range that maps to the 0-1 score
    SENSITIVITY = 60.0 
    
    # Normalize score: 0.5 represents text sitting exactly on the line
    raw_score = 0.5 + (distance / SENSITIVITY)
    
    # Clip result to strict 0.0 - 1.0 range
    final_score = max(0.0, min(1.0, raw_score))

    #visualization of the image
    cv2.line(copy_img,(0,int(best_line_y)),(img_w,int(best_line_y)),(255,0,0),2) #blue line for the printed baseline
    cv2.line(copy_img,(0,int(median_text_bottom)),(img_w,int(median_text_bottom)),(0,0,255),2) #red line for the bottom of the text
    cv2.rectangle(copy_img,(5,5),(225,50),(0,0,0),-1) #black rectangle as background for the greaded score
    cv2.putText(copy_img,f"Baseline: {final_score:.3f}",(10,30),cv2.FONT_HERSHEY_SIMPLEX,0.8,(0,0,255),2)
    return final_score,copy_img

In [21]:
def process_images_for_position(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main batch processing function: Iterates images, sorts them, and saves results to Excel
    
    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    # Sort using natural sort order (e.g., 1, 2, ... 10 instead of 1, 10, 2)
    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    
    total = len(image_files)

    print(f"Found {total} images to analyze")
    print(f"Output Excel file: {output_excel}")
    
    results = []

    for idx, img_path in enumerate(image_files, 1):
        try:
            file_id = extract_file_id(img_path.name)
            img = cv2.imread(str(img_path))

            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                results.append({
                    'ID_Number': file_id,
                    'Filename': img_path.name,
                    'Baseline': None
                })
                continue

            score,viz_img = calculate_position_score(img)
            
            # Fallback to neutral score (0.5) if detection fails
            if score is None:
                score = 0.5
                print(f"[INFO] Detection fallback for {img_path.name}")

            #saves image with results

            cv2.imwrite(os.path.join(visualization_folder,'baseline',img_path.name),viz_img)
            results.append({
                'ID_Number': file_id,
                'Filename': img_path.name,
                'Baseline': round(score, 3)
            })

            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")
            

        except Exception as e:
            print(f"[ERROR] Failed to process {img_path.name}: {str(e)}")
            results.append({
                'ID_Number': extract_file_id(img_path.name),
                'Filename': img_path.name,
                'Baseline': None
            })

    print(f"Analysis complete!")

    df = pd.DataFrame(results)
    df.to_excel(output_excel, index=False, sheet_name='Line Position')

    print(f"\nExcel file saved: {output_excel}")
    print("\nPosition Statistics (0=Cutting, 0.5=On Line, 1=Floating):")
    print(f"Min: {df['Baseline'].min():.3f}")
    print(f"Max: {df['Baseline'].max():.3f}")
    print(f"Mean: {df['Baseline'].mean():.3f}")
    print(f"Median: {df['Baseline'].median():.3f}")
    print(f"Std Dev: {df['Baseline'].std():.3f}")

    return df

In [22]:
process_images_for_position(input_dir=normalised_images_folder, output_excel=os.path.join(feature_tables_location,"Baseline.xlsx"))

Found 2512 images to analyze
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\Baseline.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\Baseline.xlsx

Position Statistics (0=Cutting, 0.5=On Line, 1=Floating):
Min: 0.000
Max: 1.000
Mean: 0.536
Median: 0.517
Std Dev: 0.079

      ID_Number        Filename  Baseline
0             1     txt (1).png     0.483
1             2     txt (2).png     0.000
2             3     txt (3).png     0.533
3             4     txt (4).png     0.483
4             5     txt (5).png     0.483
...         ...             ...       ...
2507       2520  txt (2520).png     0.550
2508       2521  txt (2521).png     0.600
2509       2522  txt (2522).png     0.483
2510       2523  txt (2523).png     0.483
2511       2524  txt (2524).png     0.575

[2512 rows x 3 columns]

### Right Margin

In [23]:
def calculate_right_margin(img: np.ndarray):
    viz_img = img.copy() if len(img.shape) == 3 else cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    height, width = img.shape[:2]

    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img.copy()

    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    min_line_width = int(width * 0.4)
    horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (min_line_width, 1))
    detected_lines = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel)
    text_only = cv2.subtract(thresh, detected_lines)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(text_only, connectivity=8)
    clean_ink = np.zeros_like(text_only)
    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        if area >= 15 and h >= 8:
            clean_ink[labels == i] = 255

    search_width = max(1, int(width * 0.973))
    col_projection = np.sum(clean_ink[:, :search_width], axis=0)
    max_density = np.max(col_projection)

    if max_density == 0:
        return 0.0, viz_img

    noise_threshold = max_density * 0.05
    ink_cols = np.where(col_projection > noise_threshold)[0]

    if len(ink_cols) == 0:
        return 0.0, viz_img

    rightmost_x = int(np.max(ink_cols))

    right_margin_pixels = width - rightmost_x
    raw_ratio = right_margin_pixels / width

    overlay = viz_img.copy()
    cv2.rectangle(overlay, (rightmost_x, 0), (width - 1, height - 1), (0, 200, 0), -1)
    cv2.addWeighted(overlay, 0.25, viz_img, 0.75, 0, viz_img)
    cv2.line(viz_img, (rightmost_x, 0), (rightmost_x, height), (0, 200, 0), 2)

    return raw_ratio, viz_img

In [24]:
def process_images_for_right_margin(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    total = len(image_files)

    print(f"Found {total} images to analyze")
    print(f"Output Excel file: {output_excel}")

    raw_ratios = []
    temp_results = []

    # Pass 1 — compute raw right-margin ratio for every image
    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path))
            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({
                    'Image_Number': idx,
                    'Filename': img_path.name,
                    'Raw_Ratio': None,
                    'viz': None
                })
                continue

            raw_ratio, viz_img = calculate_right_margin(img)
            raw_ratios.append(raw_ratio)
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Ratio': raw_ratio,
                'viz': viz_img
            })

            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] {img_path.name}: {e}")
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Ratio': None,
                'viz': None
            })

    print("Analysis complete!")

    # Pass 2 — min-max normalise across the dataset
    valid_values = [r for r in raw_ratios if r is not None]
    min_val = min(valid_values) if valid_values else 0.0
    max_val = max(valid_values) if valid_values else 1.0
    val_range = max_val - min_val

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min ratio: {min_val:.4f}")
    print(f"Raw max ratio: {max_val:.4f}")

    results = []
    for item in temp_results:
        if item['Raw_Ratio'] is None:
            normalized_value = None
        elif val_range == 0:
            normalized_value = 0.5
        else:
            normalized_value = (item['Raw_Ratio'] - min_val) / val_range

        # Save visualization with score overlay
        if item['viz'] is not None and normalized_value is not None:
            viz = item['viz']
            cv2.rectangle(viz, (5, 5), (330, 50), (0, 0, 0), -1)
            cv2.putText(viz, f"Right Margin: {normalized_value:.3f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
            cv2.imwrite(os.path.join(visualization_folder, 'right_margin', item['Filename']), viz)

        results.append({
            'Image_Number': item['Image_Number'],
            'Filename': item['Filename'],
            'Right_Margin': round(normalized_value, 3) if normalized_value is not None else None
        })

    # Save to Excel
    df = pd.DataFrame(results)
    df['Right_Margin'] = df['Right_Margin'].astype(float).round(3)
    df.to_excel(output_excel, index=False, sheet_name='Right Margin')

    # Inject Excel formula to extract numeric ID from filename  (e.g. "txt (123).png" → 123)
    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = (
            f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, '
            f'FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
        )
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nRight Margin Statistics (0=narrow, 1=wide):")
    print(f"Min:    {df['Right_Margin'].min():.3f}")
    print(f"Max:    {df['Right_Margin'].max():.3f}")
    print(f"Mean:   {df['Right_Margin'].mean():.3f}")
    print(f"Median: {df['Right_Margin'].median():.3f}")
    print(f"Std Dev:{df['Right_Margin'].std():.3f}")

    return df

In [25]:
process_images_for_right_margin(
    input_dir=normalised_images_folder,
    output_excel=os.path.join(feature_tables_location, 'right_margin.xlsx')
)

Found 2512 images to analyze
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\right_margin.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min ratio: 0.0277
Raw max ratio: 0.6277

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\right_margin.xlsx

Right Margin Statistics (0=narrow, 1=wide):
Min:    0.000
Max:    1.000
Mean:   0.134
Median: 0.108
Std Dev:0.125

      Image_Number        Filename  Right_Margin
0                1     txt (1).png         0.010
1                2     txt (2).png         0.002
2                3     txt (3).png         0.001
3                4     txt (4).png         0.001
4                5     txt (5).png         0.242
...            ...             ...           ...
2507          2508  txt (2520).png         0.029
2508          2509  txt (2521).png         0.014
2509          2510  txt (2522).png         0.770
2510          2511  txt (2523).png         0.091
2511          2512  txt (2524).png         0.083

[2512 rows x 3 columns]

### Left Margin

In [26]:
def calculate_left_margin(img: np.ndarray):
    viz_img = img.copy() if len(img.shape) == 3 else cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    height, width = img.shape[:2]

    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img.copy()

    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    min_line_width = int(width * 0.4)
    horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (min_line_width, 1))
    detected_lines = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel)
    text_only = cv2.subtract(thresh, detected_lines)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(text_only, connectivity=8)
    clean_ink = np.zeros_like(text_only)
    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        if area >= 15 and h >= 8:
            clean_ink[labels == i] = 255

    left_start = int(width * 0.027)
    col_projection = np.sum(clean_ink[:, left_start:], axis=0)
    max_density = np.max(col_projection)

    if max_density == 0:
        return 0.0, viz_img

    noise_threshold = max_density * 0.05
    ink_cols = np.where(col_projection > noise_threshold)[0]

    if len(ink_cols) == 0:
        return 0.0, viz_img

    leftmost_x = int(np.min(ink_cols)) + left_start

    raw_ratio = leftmost_x / width

    overlay = viz_img.copy()
    cv2.rectangle(overlay, (0, 0), (leftmost_x, height - 1), (0, 200, 0), -1)
    cv2.addWeighted(overlay, 0.25, viz_img, 0.75, 0, viz_img)
    cv2.line(viz_img, (leftmost_x, 0), (leftmost_x, height), (0, 200, 0), 2)

    return raw_ratio, viz_img

In [27]:
def process_images_for_left_margin(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main batch processing: calculates left margin for every image, normalises to 0-1,
    # saves results to Excel, and writes visualisation images.
    #
    # Score interpretation:
    #   0.0 = very narrow left margin (writing starts right at the left edge)
    #   1.0 = very wide left margin (large empty space on the left)

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    total = len(image_files)

    print(f"Found {total} images to analyze")
    print(f"Output Excel file: {output_excel}")

    raw_ratios = []
    temp_results = []

    # Pass 1 — compute raw left-margin ratio for every image
    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path))
            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({
                    'Image_Number': idx,
                    'Filename': img_path.name,
                    'Raw_Ratio': None,
                    'viz': None
                })
                continue

            raw_ratio, viz_img = calculate_left_margin(img)
            raw_ratios.append(raw_ratio)
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Ratio': raw_ratio,
                'viz': viz_img
            })

            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] {img_path.name}: {e}")
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Ratio': None,
                'viz': None
            })

    print("Analysis complete!")

    # Pass 2 — min-max normalise across the dataset
    valid_values = [r for r in raw_ratios if r is not None]
    min_val = min(valid_values) if valid_values else 0.0
    max_val = max(valid_values) if valid_values else 1.0
    val_range = max_val - min_val

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min ratio: {min_val:.4f}")
    print(f"Raw max ratio: {max_val:.4f}")

    results = []
    for item in temp_results:
        if item['Raw_Ratio'] is None:
            normalized_value = None
        elif val_range == 0:
            normalized_value = 0.5
        else:
            normalized_value = (item['Raw_Ratio'] - min_val) / val_range

        # Save visualization with score overlay
        if item['viz'] is not None and normalized_value is not None:
            viz = item['viz']
            cv2.rectangle(viz, (5, 5), (320, 50), (0, 0, 0), -1)
            cv2.putText(viz, f"Left Margin: {normalized_value:.3f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
            cv2.imwrite(os.path.join(visualization_folder, 'left_margin', item['Filename']), viz)

        results.append({
            'Image_Number': item['Image_Number'],
            'Filename': item['Filename'],
            'Left_Margin': round(normalized_value, 3) if normalized_value is not None else None
        })

    # Save to Excel
    df = pd.DataFrame(results)
    df['Left_Margin'] = df['Left_Margin'].astype(float).round(3)
    df.to_excel(output_excel, index=False, sheet_name='Left Margin')

    # Inject Excel formula to extract numeric ID from filename
    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = (
            f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, '
            f'FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
        )
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nLeft Margin Statistics (0=narrow, 1=wide):")
    print(f"Min:    {df['Left_Margin'].min():.3f}")
    print(f"Max:    {df['Left_Margin'].max():.3f}")
    print(f"Mean:   {df['Left_Margin'].mean():.3f}")
    print(f"Median: {df['Left_Margin'].median():.3f}")
    print(f"Std Dev:{df['Left_Margin'].std():.3f}")

    return df

In [28]:
process_images_for_left_margin(
    input_dir=normalised_images_folder,
    output_excel=os.path.join(feature_tables_location, 'left_margin.xlsx')
)

Found 2512 images to analyze
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\left_margin.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min ratio: 0.0250
Raw max ratio: 0.9240

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\left_margin.xlsx

Left Margin Statistics (0=narrow, 1=wide):
Min:    0.000
Max:    1.000
Mean:   0.345
Median: 0.334
Std Dev:0.261

      Image_Number        Filename  Left_Margin
0                1     txt (1).png        0.741
1                2     txt (2).png        0.002
2                3     txt (3).png        0.018
3                4     txt (4).png        0.750
4                5     txt (5).png        0.565
...            ...             ...          ...
2507          2508  txt (2520).png        0.582
2508          2509  txt (2521).png        0.499
2509          2510  txt (2522).png        0.072
2510          2511  txt (2523).png        0.010
2511          2512  txt (2524).png        0.489

[2512 rows x 3 columns]

### Word Spacing

In [29]:
def extract_word_boxes_from_annotated(img_bgr: np.ndarray):
    # Recovers word bounding boxes from the green rectangles drawn by the segmentation step.
    # The segmentation notebook draws cv2.rectangle(..., (0, 200, 0), 2) around each word.
    b, g, r = cv2.split(img_bgr)
    green_mask = ((g.astype(np.int32) > 150) & (r.astype(np.int32) < 80) & (b.astype(np.int32) < 80)).astype(np.uint8) * 255

    # Dilate to reconnect any broken rectangle corners
    kernel = np.ones((3, 3), np.uint8)
    green_mask = cv2.dilate(green_mask, kernel, iterations=1)

    contours, _ = cv2.findContours(green_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    boxes = []
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        if w >= 15 and h >= 8:
            boxes.append((x, y, w, h))

    return boxes


def calculate_word_spacing(img_bgr: np.ndarray):
    # Returns raw_ratio = avg_gap / avg_word_height (scale-invariant).
    # Min-max normalization across the full dataset is done in process_images_for_word_spacing.
    # Also returns viz_img with the gap regions highlighted.

    viz_img = img_bgr.copy() if len(img_bgr.shape) == 3 else cv2.cvtColor(img_bgr, cv2.COLOR_GRAY2BGR)

    boxes = extract_word_boxes_from_annotated(img_bgr)

    if len(boxes) == 0:
        return None, viz_img

    boxes_sorted = sorted(boxes, key=lambda b: b[0])
    avg_box_height = float(np.mean([h for (_, _, _, h) in boxes_sorted]))

    if len(boxes_sorted) == 1:
        return -1, viz_img  # single box: spacing is undefined

    gaps = []
    overlay = viz_img.copy()
    for i in range(len(boxes_sorted) - 1):
        x_cur, y_cur, w_cur, h_cur = boxes_sorted[i]
        x_next, y_next, w_next, h_next = boxes_sorted[i + 1]
        gap = x_next - (x_cur + w_cur)
        if gap > 0:
            gaps.append(gap)
            gap_top    = min(y_cur, y_next)
            gap_bottom = max(y_cur + h_cur, y_next + h_next)
            cv2.rectangle(overlay, (x_cur + w_cur, gap_top), (x_next, gap_bottom), (200, 100, 0), -1)

    cv2.addWeighted(overlay, 0.35, viz_img, 0.65, 0, viz_img)

    if len(gaps) == 0:
        return 0.0, viz_img

    avg_gap = float(np.median(gaps))
    raw_ratio = avg_gap / avg_box_height

    return raw_ratio, viz_img

In [30]:
def process_images_for_word_spacing(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main batch processing: calculates word spacing score for every annotated image,
    # normalises to [0, 1] via min-max across the dataset, saves results to Excel,
    # and writes visualisation images.
    #
    # Score interpretation:
    #   0.0 = tightest inter-word spacing in the dataset
    #   1.0 = widest inter-word spacing in the dataset

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    total = len(image_files)

    print(f"Found {total} images to analyze")
    print(f"Output Excel file: {output_excel}")

    raw_ratios = []
    temp_results = []

    # Pass 1 - compute raw ratio for every image
    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path))
            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({'Image_Number': extract_file_id(img_path.name),
                                     'Filename': img_path.name, 'Raw_Ratio': None, 'viz': None})
                continue

            raw_ratio, viz_img = calculate_word_spacing(img)
            if raw_ratio is not None and raw_ratio != -1:
                raw_ratios.append(raw_ratio)
            temp_results.append({'Image_Number': extract_file_id(img_path.name),
                                 'Filename': img_path.name, 'Raw_Ratio': raw_ratio, 'viz': viz_img})

            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] {img_path.name}: {e}")
            temp_results.append({'Image_Number': extract_file_id(img_path.name),
                                 'Filename': img_path.name, 'Raw_Ratio': None, 'viz': None})

    print("Analysis complete!")

    # Pass 2 - min-max normalise across the dataset
    valid_values = [r for r in raw_ratios if r is not None]
    min_val = min(valid_values) if valid_values else 0.0
    max_val = max(valid_values) if valid_values else 1.0
    val_range = max_val - min_val

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min ratio: {min_val:.4f}")
    print(f"Raw max ratio: {max_val:.4f}")

    results = []
    for item in temp_results:
        if item['Raw_Ratio'] is None:
            normalized_value = None
        elif item['Raw_Ratio'] == -1:
            normalized_value = -1  # single box detected
        elif max_val == 0:
            normalized_value = 0.0
        else:
            normalized_value = item['Raw_Ratio'] / max_val

        if item['viz'] is not None:
            viz = item['viz']
            cv2.rectangle(viz, (5, 5), (330, 50), (0, 0, 0), -1)
            label = f"Word Spacing: {normalized_value:.3f}" if normalized_value is not None else "Word Spacing: N/A"
            cv2.putText(viz, label, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
            cv2.imwrite(os.path.join(visualization_folder, 'word_spacing', item['Filename']), viz)

        results.append({'Image_Number': item['Image_Number'], 'Filename': item['Filename'],
                        'Word_Spacing': round(normalized_value, 3) if normalized_value is not None else None})

    df = pd.DataFrame(results)
    df = df.sort_values('Image_Number').reset_index(drop=True)
    df.to_excel(output_excel, index=False)

    # Inject Excel formula to extract numeric ID from filename (e.g. "txt (123).png" -> 123)
    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = (
            f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, '
            f'FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
        )
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nWord Spacing Statistics (-1=single word, 0=touching, 1=wide):")
    valid = df[df['Word_Spacing'] != -1]['Word_Spacing'].dropna()
    if len(valid) > 0:
        print(f"Min:    {valid.min():.3f}")
        print(f"Max:    {valid.max():.3f}")
        print(f"Mean:   {valid.mean():.3f}")
        print(f"Median: {valid.median():.3f}")
        print(f"Std Dev:{valid.std():.3f}")

    return df

In [31]:
segment_results_folder = r"C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/segment_results"

process_images_for_word_spacing(
    input_dir=segment_results_folder,
    output_excel=os.path.join(feature_tables_location, 'word_spacing.xlsx')
)

Found 2512 images to analyze
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\word_spacing.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min ratio: 0.1931
Raw max ratio: 3.9677

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\word_spacing.xlsx

Word Spacing Statistics (-1=single word, 0=touching, 1=wide):
Min:    0.049
Max:    1.000
Mean:   0.197
Median: 0.174
Std Dev:0.103

      Image_Number        Filename  Word_Spacing
0                1     txt (1).png         0.298
1                2     txt (2).png         0.162
2                3     txt (3).png         0.224
3                4     txt (4).png         0.102
4                5     txt (5).png         0.734
...            ...             ...           ...
2507          2520  txt (2520).png         0.224
2508          2521  txt (2521).png         0.184
2509          2522  txt (2522).png         0.304
2510          2523  txt (2523).png         0.297
2511          2524  txt (2524).png         0.584

[2512 rows x 3 columns]

### Letter Size

In [32]:
def calculate_letter_size(img_bgr: np.ndarray):
    # Extracts word bounding boxes from the green rectangles drawn by the segmentation step,
    # then returns the median box height normalized by the image height (scale-invariant raw ratio).
    # Min-max normalization across the full dataset is done in process_images_for_letter_size.
    # Also returns viz_img with each box height annotated.

    viz_img = img_bgr.copy() if len(img_bgr.shape) == 3 else cv2.cvtColor(img_bgr, cv2.COLOR_GRAY2BGR)
    img_height = img_bgr.shape[0]

    boxes = extract_word_boxes_from_annotated(img_bgr)

    if len(boxes) == 0:
        return None, viz_img

    heights = [h for (_, _, _, h) in boxes]
    median_height = float(np.median(heights))

    # Normalize by image height so the ratio is scale-invariant across different image sizes
    raw_ratio = median_height / img_height

    # Draw each word box on the visualization
    overlay = viz_img.copy()
    for (x, y, w, h) in boxes:
        cv2.rectangle(overlay, (x, y), (x + w, y + h), (0, 200, 0), 2)
    cv2.addWeighted(overlay, 0.6, viz_img, 0.4, 0, viz_img)

    return raw_ratio, viz_img

In [33]:
def process_images_for_letter_size(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main batch processing: calculates absolute letter size for every annotated image,
    # normalises to [0, 1] via min-max across the dataset, saves results to Excel,
    # and writes visualisation images.
    #
    # Score interpretation:
    #   0.0 = very small letters (minimum size in dataset)
    #   0.5 = medium / standard letter height
    #   1.0 = very large letters (dominant, fills the line)

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    total = len(image_files)

    print(f"Found {total} images to analyze")
    print(f"Output Excel file: {output_excel}")

    raw_ratios = []
    temp_results = []

    # Pass 1 — compute raw ratio for every image
    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path))
            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({'Image_Number': extract_file_id(img_path.name),
                                     'Filename': img_path.name, 'Raw_Ratio': None, 'viz': None})
                continue

            raw_ratio, viz_img = calculate_letter_size(img)
            if raw_ratio is not None:
                raw_ratios.append(raw_ratio)
            temp_results.append({'Image_Number': extract_file_id(img_path.name),
                                 'Filename': img_path.name, 'Raw_Ratio': raw_ratio, 'viz': viz_img})

            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] {img_path.name}: {e}")
            temp_results.append({'Image_Number': extract_file_id(img_path.name),
                                 'Filename': img_path.name, 'Raw_Ratio': None, 'viz': None})

    print("Analysis complete!")

    # Pass 2 — min-max normalise across the dataset
    valid_values = [r for r in raw_ratios if r is not None]
    min_val = min(valid_values) if valid_values else 0.0
    max_val = max(valid_values) if valid_values else 1.0
    val_range = max_val - min_val

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min ratio: {min_val:.4f}")
    print(f"Raw max ratio: {max_val:.4f}")

    results = []
    for item in temp_results:
        if item['Raw_Ratio'] is None:
            normalized_value = None
        elif val_range == 0:
            normalized_value = 0.5
        else:
            normalized_value = (item['Raw_Ratio'] - min_val) / val_range

        # Save visualization with score overlay
        if item['viz'] is not None and normalized_value is not None:
            viz = item['viz']
            cv2.rectangle(viz, (5, 5), (330, 50), (0, 0, 0), -1)
            cv2.putText(viz, f"Letter Size: {normalized_value:.3f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
            cv2.imwrite(os.path.join(visualization_folder, 'letter_size', item['Filename']), viz)

        results.append({'Image_Number': item['Image_Number'], 'Filename': item['Filename'],
                        'Letter_Size': round(normalized_value, 3) if normalized_value is not None else None})

    df = pd.DataFrame(results)
    df = df.sort_values('Image_Number').reset_index(drop=True)
    df.to_excel(output_excel, index=False)

    # Inject Excel formula to extract numeric ID from filename (e.g. "txt (123).png" -> 123)
    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = (
            f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, '
            f'FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
        )
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nLetter Size Statistics (0=small, 0.5=medium, 1=large):")
    valid = df['Letter_Size'].dropna()
    if len(valid) > 0:
        print(f"Min:    {valid.min():.3f}")
        print(f"Max:    {valid.max():.3f}")
        print(f"Mean:   {valid.mean():.3f}")
        print(f"Median: {valid.median():.3f}")
        print(f"Std Dev:{valid.std():.3f}")

    return df

In [34]:
segment_results_folder = r"C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/segment_results"

process_images_for_letter_size(
    input_dir=segment_results_folder,
    output_excel=os.path.join(feature_tables_location, 'letter_size.xlsx')
)

Found 2512 images to analyze
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\letter_size.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min ratio: 0.0925
Raw max ratio: 0.7471

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\letter_size.xlsx

Letter Size Statistics (0=small, 0.5=medium, 1=large):
Min:    0.000
Max:    1.000
Mean:   0.560
Median: 0.553
Std Dev:0.148

      Image_Number        Filename  Letter_Size
0                1     txt (1).png        0.578
1                2     txt (2).png        0.572
2                3     txt (3).png        0.605
3                4     txt (4).png        0.502
4                5     txt (5).png        0.525
...            ...             ...          ...
2507          2520  txt (2520).png        0.473
2508          2521  txt (2521).png        0.591
2509          2522  txt (2522).png        0.287
2510          2523  txt (2523).png        0.454
2511          2524  txt (2524).png        0.581

[2512 rows x 3 columns]

## Word Aspect Ratio

In [35]:
def remove_printed_text_and_lines(img: np.ndarray) -> np.ndarray:
    # Preprocesses image to remove horizontal ruled lines and noise, isolating handwriting
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img

    # Create binary inverse (white text on black background)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)
    height, width = img.shape[:2]

    # Detect and remove horizontal lines using Hough Transform
    lines_mask = np.zeros_like(binary)
    lines = cv2.HoughLinesP(binary, 1, np.pi/180, threshold=100, minLineLength=width*0.3, maxLineGap=10)
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            # Draw thick lines over detected ruled lines to mask them
            cv2.line(lines_mask, (x1, y1), (x2, y2), 255, 8)

    # Subtract lines from the binary image
    binary_no_lines = cv2.bitwise_and(binary, cv2.bitwise_not(lines_mask))
    
    # Filter out noise and irrelevant regions using Connected Components
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(binary_no_lines, connectivity=8)
    handwriting_mask = np.zeros_like(binary_no_lines)

    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        # Define regions to ignore (header, footer) and noise threshold
        is_bottom_region = (y + h) > height * 0.85
        is_top_region = y < height * 0.1
        is_too_small = area < 15

        # Keep only valid handwriting components
        if not (is_bottom_region or is_top_region or is_too_small):
            handwriting_mask[labels == i] = 255

    # Invert back to normal (black text on white background)
    result = cv2.bitwise_not(handwriting_mask)
    return result

In [36]:
def calculate_dimension_raw(img: np.ndarray) -> float:
    # Calculates the raw Height/Width ratio using the median of handwriting blobs
    handwriting_only = remove_printed_text_and_lines(img)

    if len(handwriting_only.shape) == 3:
        gray = cv2.cvtColor(handwriting_only, cv2.COLOR_BGR2GRAY)
    else:
        gray = handwriting_only

    # Binary thresholding (invert so text is white)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)

    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    heights = []
    widths = []

    for c in contours:
        if cv2.contourArea(c) > 20:
            x, y, w, h = cv2.boundingRect(c)
            # Filter out tiny noise that might skew the median
            if w > 3 and h > 3:
                widths.append(w)
                heights.append(h)

    if not heights or not widths:
        return None

    median_h = np.median(heights)
    median_w = np.median(widths)

    if median_w == 0:
        return None

    # Calculate raw ratio
    raw_ratio = median_h / median_w

    return raw_ratio

In [37]:
def process_images_for_word_aspect_ratio(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main processing loop: iterates images, calculates raw dimension, and normalizes results

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files))
    total = len(image_files)

    print(f"Found {total} images to analyze for Dimension feature")
    print(f"Output Excel file: {output_excel}")
    
    raw_dimension_values = []
    temp_results = []

    # Ensure visualization folder for dimension exists
    vis_dir = os.path.join(visualization_folder, 'word_aspect_ratio')
    if not os.path.exists(vis_dir):
        os.makedirs(vis_dir)

    # Step 1: Calculate raw dimension for all images
    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)

            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({
                    'Image_Number': idx,
                    'Filename': img_path.name,
                    'Raw_Dimension': None
                })
                continue

            dimension_ratio = calculate_dimension_raw(img)
            
            if dimension_ratio is not None:
                raw_dimension_values.append(dimension_ratio)

            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Dimension': dimension_ratio
            })
            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] Failed to process {img_path.name}: {str(e)}")
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Dimension': None
            })

    print(f"Analysis complete!")

    # Step 2: Normalize values to 0-1 range based on dataset min/max
    valid_values = [r for r in raw_dimension_values if r is not None and r > 0]
    min_dim = min(valid_values) if valid_values else 0.0
    max_dim = max(valid_values) if valid_values else 1.0
    dim_range = max_dim - min_dim

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min (widest letters): {min_dim:.3f}")
    print(f"Raw max (tallest letters): {max_dim:.3f}")

    results = []
    for item in temp_results:
        if item['Raw_Dimension'] is None:
            normalized_value = None
        elif dim_range == 0:
            normalized_value = 0.5
        else:
            # Min-Max Normalization formula
            normalized_value = (item['Raw_Dimension'] - min_dim) / dim_range

        results.append({
            'Image_Number': item['Image_Number'],
            'Filename': item['Filename'],
            'Dimension': round(normalized_value, 3) if normalized_value is not None else None
        })
        
        # saving visualization of the results for better understanding
        if normalized_value is not None:
            path = os.path.join(normalised_images_folder, item['Filename'])
            img = cv2.imread(path)
            if img is not None:
                cv2.rectangle(img, (5, 5), (310, 50), (0, 0, 0), -1)
                cv2.putText(img, f"Dimension: {normalized_value:.3f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
                cv2.imwrite(os.path.join(vis_dir, item['Filename']), img)

    # Save to Excel
    df = pd.DataFrame(results)
    
    # Ensuring the results are rounded to 3 decimal
    df['Dimension'] = df['Dimension'].astype(float).round(3)
    df.to_excel(output_excel, index=False, sheet_name='Dimension')

    # Add the formula for ID parsing using openpyxl
    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nNormalized Dimension Statistics (0-1 range):")
    print(f"Min: {df['Dimension'].min():.3f}")
    print(f"Max: {df['Dimension'].max():.3f}")
    print(f"Mean: {df['Dimension'].mean():.3f}")
    print(f"Median: {df['Dimension'].median():.3f}")
    print(f"Std Dev: {df['Dimension'].std():.3f}")

    return df

In [38]:
process_images_for_word_aspect_ratio(input_dir=normalised_images_folder, output_excel=os.path.join(feature_tables_location, 'word_aspect_ratio.xlsx'))

Found 2512 images to analyze for Dimension feature
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\word_aspect_ratio.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min (widest letters): 0.405
Raw max (tallest letters): 7.200

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\word_aspect_ratio.xlsx

Normalized Dimension Statistics (0-1 range):
Min: 0.000
Max: 1.000
Mean: 0.155
Median: 0.139
Std Dev: 0.087

      Image_Number        Filename  Dimension
0                1     txt (1).png      0.186
1                2    txt (10).png      0.110
2                3   txt (100).png      0.212
3                4  txt (1000).png      0.109
4                5  txt (1001).png      0.098
...            ...             ...        ...
2507          2508   txt (995).png      0.148
2508          2509   txt (996).png      0.138
2509          2510   txt (997).png      0.122
2510          2511   txt (998).png      0.141
2511          2512   txt (999).png      0.152

[2512 rows x 3 columns]

## Basline Slope

In [39]:
USER_MIN_COMPONENT_AREA = 20
USER_MIN_COMPONENT_WIDTH = 3
USER_MIN_COMPONENT_HEIGHT = 4
USER_MIN_DENSITY = 0.18
USER_MIN_NEIGHBOR_SUPPORT = 2
USER_NEIGHBOR_RADIUS_X = 25
USER_NEIGHBOR_RADIUS_Y = 18


def remove_printed_text_and_lines(img: np.ndarray) -> np.ndarray:
    # Preprocesses image to remove horizontal ruled lines and noise, isolating handwriting
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img

    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    _, binary = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    height, width = gray.shape[:2]

    lines_mask = np.zeros_like(binary)
    lines = cv2.HoughLinesP(binary, 1, np.pi/180, threshold=100, minLineLength=int(width * 0.30), maxLineGap=10)
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            if abs(y2 - y1) <= 3:
                cv2.line(lines_mask, (x1, y1), (x2, y2), 255, 8)

    binary_no_lines = cv2.bitwise_and(binary, cv2.bitwise_not(lines_mask))

    kernel_open = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
    binary_no_lines = cv2.morphologyEx(binary_no_lines, cv2.MORPH_OPEN, kernel_open, iterations=1)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(binary_no_lines, connectivity=8)
    handwriting_mask = np.zeros_like(binary_no_lines)

    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        density = area / max(w * h, 1)
        is_bottom_region = (y + h) > height * 0.92
        is_top_region = y < height * 0.03
        is_too_small = area < USER_MIN_COMPONENT_AREA
        is_too_thin = w < USER_MIN_COMPONENT_WIDTH or h < USER_MIN_COMPONENT_HEIGHT
        is_too_sparse = density < USER_MIN_DENSITY

        if not (is_bottom_region or is_top_region or is_too_small or is_too_thin or is_too_sparse):
            handwriting_mask[labels == i] = 255

    result = cv2.bitwise_not(handwriting_mask)
    return result


def extract_file_id(filename: str) -> int:
    match = re.search(r'(\d+)', filename)
    if match:
        return int(match.group(1))
    return -1


def get_letter_centroids(img: np.ndarray):
    # Extracts letter-like connected components and keeps only concentrated pixels with local support
    handwriting_only = remove_printed_text_and_lines(img)

    if len(handwriting_only.shape) == 3:
        gray = cv2.cvtColor(handwriting_only, cv2.COLOR_BGR2GRAY)
    else:
        gray = handwriting_only

    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)
    height, width = binary.shape[:2]

    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(binary, connectivity=8)

    candidates = []
    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        cx, cy = centroids[i]
        density = area / max(w * h, 1)

        if area < USER_MIN_COMPONENT_AREA:
            continue
        if w < USER_MIN_COMPONENT_WIDTH or h < USER_MIN_COMPONENT_HEIGHT:
            continue
        if density < USER_MIN_DENSITY:
            continue
        if y < height * 0.03 or (y + h) > height * 0.92:
            continue

        candidates.append({
            'x': x,
            'y': y,
            'w': w,
            'h': h,
            'cx': float(cx),
            'cy': float(cy),
            'area': area,
            'density': float(density)
        })

    letters = []
    for i, comp in enumerate(candidates):
        neighbors = 0
        for j, other in enumerate(candidates):
            if i == j:
                continue
            if abs(comp['cx'] - other['cx']) <= USER_NEIGHBOR_RADIUS_X and abs(comp['cy'] - other['cy']) <= USER_NEIGHBOR_RADIUS_Y:
                neighbors += 1
        if neighbors >= USER_MIN_NEIGHBOR_SUPPORT:
            letters.append(comp)

    letters = sorted(letters, key=lambda d: d['cx'], reverse=True)
    return letters


def calculate_baseline_slope_raw(img: np.ndarray) -> float:
    # Calculates raw line flow direction using linear regression on concentrated letter centroids (RTL aware)
    letters = get_letter_centroids(img)

    if len(letters) < 2:
        return None

    xs = np.array([l['cx'] for l in letters], dtype=np.float32)
    ys = np.array([l['cy'] for l in letters], dtype=np.float32)

    try:
        m, b = np.polyfit(xs, ys, 1)
    except Exception:
        return None

    right_x = np.max(xs)
    left_x = np.min(xs)
    right_y = m * right_x + b
    left_y = m * left_x + b

    raw_diff = right_y - left_y
    return float(raw_diff)

In [40]:
def process_images_for_baseline_slope(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:
    # Main processing loop: iterates images, calculates raw slope from concentrated letter centroids, and normalizes results

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    total = len(image_files)

    print(f"Found {total} images to analyze for Baseline Slope feature")
    print(f"Output Excel file: {output_excel}")

    raw_slope_values = []
    temp_results = []

    vis_dir = os.path.join(visualization_folder, 'baseline_slope')
    if not os.path.exists(vis_dir):
        os.makedirs(vis_dir)

    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)

            if img is None:
                print(f"[WARNING] Could not read: {img_path.name}")
                temp_results.append({
                    'Image_Number': idx,
                    'Filename': img_path.name,
                    'Raw_Slope': None
                })
                continue

            raw_slope = calculate_baseline_slope_raw(img)

            if raw_slope is not None:
                raw_slope_values.append(raw_slope)

            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Slope': raw_slope
            })
            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] Failed to process {img_path.name}: {str(e)}")
            temp_results.append({
                'Image_Number': idx,
                'Filename': img_path.name,
                'Raw_Slope': None
            })

    print(f"Analysis complete!")

    valid_values = [r for r in raw_slope_values if r is not None]
    min_slope = min(valid_values) if valid_values else 0.0
    max_slope = max(valid_values) if valid_values else 1.0
    slope_range = max_slope - min_slope

    print(f"\nNormalizing to [0, 1] range:")
    print(f"Raw min (falling): {min_slope:.3f}")
    print(f"Raw max (climbing): {max_slope:.3f}")

    results = []
    for item in temp_results:
        if item['Raw_Slope'] is None:
            normalized_value = 0.5
        elif slope_range == 0:
            normalized_value = 0.5
        else:
            normalized_value = (item['Raw_Slope'] - min_slope) / slope_range

        results.append({
            'Image_Number': item['Image_Number'],
            'Filename': item['Filename'],
            'Baseline_Slope': round(normalized_value, 3)
        })

        path = os.path.join(normalised_images_folder, item['Filename'])
        img_vis = cv2.imread(path)
        if img_vis is not None:
            cv2.rectangle(img_vis, (5, 5), (300, 55), (0, 0, 0), -1)

            letters = get_letter_centroids(cv2.imread(path, cv2.IMREAD_GRAYSCALE))
            if len(letters) >= 2:
                xs = np.array([l['cx'] for l in letters], dtype=np.float32)
                ys = np.array([l['cy'] for l in letters], dtype=np.float32)
                m, b = np.polyfit(xs, ys, 1)
                right_x = int(np.max(xs))
                left_x = int(np.min(xs))
                right_y = int(m * right_x + b)
                left_y = int(m * left_x + b)
                cv2.line(img_vis, (right_x, right_y), (left_x, left_y), (0, 0, 255), 2)
                for l in letters:
                    cv2.circle(img_vis, (int(l['cx']), int(l['cy'])), 2, (255, 0, 0), -1)

            label_text = f"Baseline_Slope: {normalized_value:.3f}"
            cv2.putText(img_vis, label_text, (10, 32), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)
            cv2.imwrite(os.path.join(vis_dir, item['Filename']), img_vis)

    df = pd.DataFrame(results)
    df['Baseline_Slope'] = pd.to_numeric(df['Baseline_Slope'], errors='coerce').round(3)
    df.to_excel(output_excel, index=False, sheet_name='Baseline Slope')

    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = extract_file_id(ws[f'B{row_num}'].value)
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nNormalized Baseline Slope Statistics (0-1 range):")
    print(f"Min: {df['Baseline_Slope'].min():.3f}")
    print(f"Max: {df['Baseline_Slope'].max():.3f}")
    print(f"Mean: {df['Baseline_Slope'].mean():.3f}")
    print(f"Median: {df['Baseline_Slope'].median():.3f}")
    print(f"Std Dev: {df['Baseline_Slope'].std():.3f}")

    return df

In [41]:
process_images_for_baseline_slope(input_dir=normalised_images_folder,output_excel=os.path.join(feature_tables_location, 'baseline_slope.xlsx'))

Found 2512 images to analyze for Baseline Slope feature
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\baseline_slope.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing to [0, 1] range:
Raw min (falling): -67.476
Raw max (climbing): 58.401

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\baseline_slope.xlsx

Normalized Baseline Slope Statistics (0-1 range):
Min: 0.000
Max: 1.000
Mean: 0.532
Median: 0.523
Std Dev: 0.064

      Image_Number        Filename  Baseline_Slope
0                1     txt (1).png           0.485
1                2     txt (2).png           0.722
2                3     txt (3).png           0.500
3                4     txt (4).png           0.500
4                5     txt (5).png           0.538
...            ...             ...             ...
2507          2508  txt (2520).png           0.541
2508          2509  txt (2521).png           0.541
2509          2510  txt (2522).png           0.500
2510          2511  txt (2523).png           0.525
2511          2512  txt (2524).png           0.538

[2512 rows x 3 columns]

# Roundness vs. Angularity

In [42]:
USER_MIN_PERCENTILE = 5
USER_MAX_PERCENTILE = 95

# קרנל "תפירה" א-סימטרי: 6 לרוחב, 8 לגובה. 
# הגובה הגדול יותר נועד "לרפא" את החתך האופקי שנוצר בעקבות מחיקת השורה המודפסת.
USER_CLOSING_KERNEL_SIZE = (6, 8) 

USER_MIN_HOLE_AREA = 7
# ==========================================

def extract_file_id(filename: str) -> int:
    match = re.search(r'(\d+)', filename)
    if match:
        return int(match.group(1))
    return -1

def remove_printed_text_and_lines(img: np.ndarray) -> np.ndarray:
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img

    # OTSU לשמירה על שלמות הדיו של הכותב
    _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    height, width = img.shape[:2]

    lines_mask = np.zeros_like(binary)
    lines = cv2.HoughLinesP(binary, 1, np.pi/180, threshold=100, minLineLength=width*0.3, maxLineGap=10)
    
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            # === השינוי: מחיקה כירורגית דקה (3 פיקסלים) במקום 8 עבים ===
            cv2.line(lines_mask, (x1, y1), (x2, y2), 255, 3)

    # החסרת הקווים
    binary_no_lines = cv2.bitwise_and(binary, cv2.bitwise_not(lines_mask))
    
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(binary_no_lines, connectivity=8)
    handwriting_mask = np.zeros_like(binary_no_lines)

    for i in range(1, num_labels):
        x, y, w, h, area = stats[i]
        is_bottom_region = (y + h) > height * 0.85
        is_top_region = y < height * 0.1
        is_too_small = area < 15

        if not (is_bottom_region or is_top_region or is_too_small):
            handwriting_mask[labels == i] = 255

    result = cv2.bitwise_not(handwriting_mask)
    return result

In [43]:
def calculate_roundness_raw(img: np.ndarray, filename: str, vis_dir: str = None) -> float:
    # 1. הפעלת מחיקת השורות המודפסות
    handwriting_only = remove_printed_text_and_lines(img)

    if len(handwriting_only.shape) == 3:
        gray = cv2.cvtColor(handwriting_only, cv2.COLOR_BGR2GRAY)
    else:
        gray = handwriting_only

    # המרה לבינארי שוב אחרי הניקוי
    _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

    # 2. איחוי ותפירת חתכים (כולל החתך שהשארנו ממחיקת השורה)
    close_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, USER_CLOSING_KERNEL_SIZE)
    closed_bin = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, close_kernel)

    # 3. מציאת קווי מתאר והיררכיה (לאיתור חללים)
    contours, hierarchy = cv2.findContours(closed_bin, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

    if hierarchy is None:
        return 0.500

    circularities = []
    debug_img = None
    if vis_dir:
        debug_img = img.copy() if len(img.shape) == 3 else cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

    for i, c in enumerate(contours):
        parent_idx = hierarchy[0][i][3]
        
        # זיהוי חור
        if parent_idx != -1: 
            area = cv2.contourArea(c)
            # סינון רעשים ואזורים גדולים מדי
            if USER_MIN_HOLE_AREA < area < 3000:
                perimeter = cv2.arcLength(c, True)
                
                if perimeter > 0:
                    circularity = (4 * np.pi * area) / (perimeter ** 2)
                    circularity = min(1.0, circularity)
                    circularities.append(circularity)

                    if debug_img is not None:
                        green = int(circularity * 255)
                        red = int((1 - circularity) * 255)
                        cv2.drawContours(debug_img, [c], -1, (0, green, red), 2)

    if not circularities:
        if vis_dir and debug_img is not None:
            cv2.putText(debug_img, "No Holes Found. Assigned Default 0.500", (10, 30), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)
            cv2.imwrite(os.path.join(vis_dir, f"{filename}"), debug_img)
        return 0.500

    median_circularity = np.median(circularities)

    if vis_dir and debug_img is not None:
        cv2.putText(debug_img, f"Raw Roundness: {median_circularity:.3f}", (10, 30), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 0), 2)
        cv2.imwrite(os.path.join(vis_dir, f"{filename}"), debug_img)

    return median_circularity

In [44]:
def process_images_for_roundness(
    input_dir: str,
    output_excel: str,
    extensions: tuple = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
) -> pd.DataFrame:

    image_files = set()
    for ext in extensions:
        image_files.update(Path(input_dir).glob(f'*{ext}'))
        image_files.update(Path(input_dir).glob(f'*{ext.upper()}'))

    image_files = sorted(list(image_files), key=lambda p: extract_file_id(p.name))
    total = len(image_files)

    print(f"Found {total} images to analyze for Roundness vs. Angularity (No-Lines Mode)")
    print(f"Output Excel file: {output_excel}")
    
    raw_circ_values = []
    temp_results = []

    vis_dir = os.path.join(visualization_folder, 'roundness')
    if not os.path.exists(vis_dir):
        os.makedirs(vis_dir)

    for idx, img_path in enumerate(image_files, 1):
        try:
            img = cv2.imread(str(img_path))
            if img is None:
                temp_results.append({'Filename': img_path.name, 'Raw_Roundness': None})
                continue

            circ = calculate_roundness_raw(img, img_path.name, vis_dir)
            
            if circ is not None:
                raw_circ_values.append(circ)

            temp_results.append({
                'Filename': img_path.name,
                'Raw_Roundness': circ
            })
            if idx % 500 == 0:
                print(f"Processed {idx}/{total} images...")

        except Exception as e:
            print(f"[ERROR] Failed to process {img_path.name}: {str(e)}")
            temp_results.append({'Filename': img_path.name, 'Raw_Roundness': None})

    print(f"Analysis complete!")

    valid_values_for_norm = [r for r in raw_circ_values if r is not None and r != 0.500]
    
    if valid_values_for_norm:
        min_circ = np.percentile(valid_values_for_norm, USER_MIN_PERCENTILE)
        max_circ = np.percentile(valid_values_for_norm, USER_MAX_PERCENTILE)
    else:
        min_circ, max_circ = 0.0, 1.0
        
    circ_range = max_circ - min_circ
    if circ_range <= 0: circ_range = 1.0 

    print(f"\nNormalizing Circularity:")
    print(f"Most Angular Threshold (0.0): {min_circ:.3f}")
    print(f"Most Round Threshold (1.0): {max_circ:.3f}")

    results = []
    for item in temp_results:
        filename = item['Filename']
        file_id = extract_file_id(filename)
        
        if item['Raw_Roundness'] is None:
            normalized_value = None
        elif item['Raw_Roundness'] == 0.500:
             normalized_value = 0.500
        else:
            raw_val = item['Raw_Roundness']
            norm = (raw_val - min_circ) / circ_range
            normalized_value = max(0.0, min(1.0, norm))

        results.append({
            'ID_Number': file_id,
            'Filename': filename,
            'Roundness_Score': round(normalized_value, 3) if normalized_value is not None else None
        })
        
        if normalized_value is not None:
            path = os.path.join(vis_dir, filename)
            if os.path.exists(path):
                img_debug = cv2.imread(path)
                cv2.rectangle(img_debug, (5, 5), (310, 50), (0, 0, 0), -1)
                
                if item['Raw_Roundness'] == 0.500:
                    text_color = (0, 255, 255) 
                    label_text = f"Score: 0.500 (No Holes Detected)"
                else:
                    text_color = (0, 255, 0) if normalized_value > 0.6 else ((0, 0, 255) if normalized_value < 0.4 else (0, 255, 255))
                    label_text = f"Roundness Score: {normalized_value:.3f}"
                    
                cv2.putText(img_debug, label_text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, text_color, 2)
                cv2.imwrite(path, img_debug)

    df = pd.DataFrame(results)
    df['Roundness_Score'] = df['Roundness_Score'].astype(float).round(3)
    df.to_excel(output_excel, index=False, sheet_name='Roundness')

    wb = load_workbook(output_excel)
    ws = wb.active
    for row_num in range(2, len(results) + 2):
        ws[f'A{row_num}'] = f'=VALUE(MID(B{row_num}, FIND("(",B{row_num})+1, FIND(")",B{row_num})-FIND("(",B{row_num})-1))'
    wb.save(output_excel)

    print(f"\nExcel file saved: {output_excel}")
    print("\nNormalized Roundness Statistics:")
    print(f"Min: {df['Roundness_Score'].min():.3f}")
    print(f"Max: {df['Roundness_Score'].max():.3f}")
    print(f"Mean: {df['Roundness_Score'].mean():.3f}")
    print(f"Median: {df['Roundness_Score'].median():.3f}")

    return df

In [45]:
process_images_for_roundness(
    input_dir=normalised_images_folder, 
    output_excel=os.path.join(feature_tables_location, 'roundness.xlsx')
)

Found 2512 images to analyze for Roundness vs. Angularity (No-Lines Mode)
Output Excel file: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\roundness.xlsx
Processed 500/2512 images...
Processed 1000/2512 images...
Processed 1500/2512 images...
Processed 2000/2512 images...
Processed 2500/2512 images...
Analysis complete!

Normalizing Circularity:
Most Angular Threshold (0.0): 0.717
Most Round Threshold (1.0): 0.889

Excel file saved: C:/Users/ranor/Desktop/ocr/Handwriting-OCR-for-Graphology/tables\roundness.xlsx

Normalized Roundness Statistics:
Min: 0.000
Max: 1.000
Mean: 0.576
Median: 0.500

      ID_Number        Filename  Roundness_Score
0             1     txt (1).png            0.500
1             2     txt (2).png            0.948
2             3     txt (3).png            0.500
3             4     txt (4).png            0.500
4             5     txt (5).png            0.500
...         ...             ...              ...
2507       2520  txt (2520).png            0.924
2508       2521  txt (2521).png            1.000
2509       2522  txt (2522).png            0.500
2510       2523  txt (2523).png            0.500
2511       2524  txt (2524).png            0.500

[2512 rows x 3 columns]

## Unified Feature Table

Merge all per-feature Excel files into a single table — one row per image, one column per feature.

In [46]:
import pandas as pd
import os
import re
import numpy as np

feature_tables_location = 'tables'

# (excel_filename, filename_col, source_feat_col, output_col_name)
feature_files = [
    ('Baseline.xlsx',          'Filename',  'Baseline',         'Baseline'),
    ('baseline_slope.xlsx',    'Filename',  'Baseline_Slope',   'Baseline_Slope'),
    ('left_margin.xlsx',       'Filename',  'Left_Margin',      'Left_Margin'),
    ('right_margin.xlsx',      'Filename',  'Right_Margin',     'Right_Margin'),
    ('letter_size.xlsx',       'Filename',  'Letter_Size',      'Letter_Size'),
    ('word_spacing.xlsx',      'Filename',  'Word_Spacing',     'Word_Spacing'),
    ('slant.xlsx',             'File Name', 'Slant',            'Slant'),
    ('stroke_thickness.xlsx',  'Filename',  'Stroke_Thickness', 'Stroke_Thickness'),
    ('word_aspect_ratio.xlsx', 'Filename',  'Dimension',        'Word_Aspect_Ratio'),
    ('roundness.xlsx',         'Filename',  'Roundness_Score',  'Roundness'),
]

merged = None
for fname, fn_col, src_col, out_col in feature_files:
    df = pd.read_excel(os.path.join(feature_tables_location, fname))
    df = df[[fn_col, src_col]].copy()
    df.rename(columns={fn_col: 'Filename', src_col: out_col}, inplace=True)
    df = df.groupby('Filename', as_index=False)[out_col].mean()
    merged = df if merged is None else merged.merge(df, on='Filename', how='outer')

def extract_id(fn):
    m = re.search(r'\((\d+)\)', str(fn))
    return int(m.group(1)) if m else None

merged.insert(0, 'Image_ID', merged['Filename'].apply(extract_id))
merged.sort_values('Image_ID', inplace=True)
merged.reset_index(drop=True, inplace=True)

# Average row: ignore -1 values and non-feature columns
feature_cols = [c for c in merged.columns if c not in ('Image_ID', 'Filename')]
avg_values = {
    col: merged[col].replace(-1, np.nan).mean()
    for col in feature_cols
}
avg_row = pd.DataFrame([{'Image_ID': 'Average', 'Filename': 'Average', **avg_values}])
merged = pd.concat([merged, avg_row], ignore_index=True)

output_path = os.path.join(feature_tables_location, 'all_features.xlsx')
merged.to_excel(output_path, index=False)

print(f'Saved to: {output_path}  |  Shape: {merged.shape}')
merged

Saved to: tables\all_features.xlsx  |  Shape: (2513, 12)

,Image_ID,Filename,Baseline,Baseline_Slope,Left_Margin,Right_Margin,Letter_Size,Word_Spacing,Slant,Stroke_Thickness,Word_Aspect_Ratio,Roundness
0,1,txt (1).png,0.483000,0.485000,0.741000,0.010000,0.578000,0.29800,0.433000,0.368000,0.186000,0.500000
1,2,txt (2).png,0.000000,0.722000,0.002000,0.002000,0.572000,0.16200,0.388000,0.254000,0.101000,0.948000
2,3,txt (3).png,0.533000,0.500000,0.018000,0.001000,0.605000,0.22400,0.466000,0.277000,0.349000,0.500000
3,4,txt (4).png,0.483000,0.500000,0.750000,0.001000,0.502000,0.10200,0.397000,0.401000,0.088000,0.500000
4,5,txt (5).png,0.483000,0.538000,0.565000,0.242000,0.525000,0.73400,1.000000,0.298000,0.078000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...
2508,2521,txt (2521).png,0.600000,0.541000,0.499000,0.014000,0.591000,0.18400,0.460000,0.174000,0.156000,1.000000
2509,2522,txt (2522).png,0.483000,0.500000,0.072000,0.770000,0.287000,0.30400,0.470000,0.149000,0.210000,0.500000
2510,2523,txt (2523).png,0.483000,0.525000,0.010000,0.091000,0.454000,0.29700,0.480000,0.329000,0.104000,0.500000
2511,2524,txt (2524).png,0.575000,0.538000,0.489000,0.083000,0.581000,0.58400,0.593000,0.149000,0.110000,0.500000
2512,Average,Average,0.535786,0.531781,0.345417,0.134338,0.560184,0.19716,0.534663,0.294387,0.154889,0.575997

## Graphological Report

Send the unified feature table to Claude Opus and receive a full personal graphological report.

In [47]:
import anthropic
import pandas as pd
import os
import numpy as np
from getpass import getpass

# ── API key ──────────────────────────────────────────────────────────────
_api_key = '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'

# ── 1. Load the unified feature table and extract the average row ───────────
df = pd.read_excel(os.path.join(feature_tables_location, 'all_features.xlsx'))
avg = df[df['Image_ID'] == 'Average'].iloc[0]

feature_meta = {
    'Baseline':          ('היצמדות לשורה – אזור כתיבה',        '0=אזור תחתון, 0.5=על השורה, 1=אזור עליון'),
    'Baseline_Slope':    ('שיפוע קו הבסיס',                    '0=שורה יורדת, 0.5=שורה ישרה, 1=שורה עולה'),
    'Left_Margin':       ('שולי שמאל – שולי סיום',             '0=ללא שוליים, 0.5=תקני ~2 ס"מ, 1=רחב מאוד'),
    'Right_Margin':      ('שולי ימין – שולי פתיחה',            '0=ללא שוליים, 0.5=תקני ~2 ס"מ, 1=רחב מאוד'),
    'Letter_Size':       ('גודל הכתב האבסולוטי',               '0=זעיר, 0.5=בינוני ~3 מ"מ, 1=ענק'),
    'Word_Spacing':      ('מרווח בין מילים',                   '0=צפוף, 0.5=תקני ~2 אותיות, 1=מרווח עצום'),
    'Slant':             ('נטיית הכתב',                        '0=שמאלה, 0.5=אנכי, 1=ימינה'),
    'Stroke_Thickness':  ('עובי קו – לחץ כתיבה',              '0=דקיק, 0.5=בינוני, 1=עבה'),
    'Word_Aspect_Ratio': ('יחס רוחב-גובה של המילים',          '0=צר/גבוה, 0.5=פרופורציונלי 1:1, 1=רחב/שטוח'),
    'Roundness':         ('מעגליות מול זוויתיות',              '0=זוויתי מאוד, 0.5=תקני, 1=עגול מאוד'),
}

features_text = "\n".join(
    f"• {desc}  [{scale}]  →  {float(avg[col]):.3f}"
    for col, (desc, scale) in feature_meta.items()
    if col in avg.index and pd.notna(avg[col]) and float(avg[col]) != -1
)

# ── 2. Graphology dictionary (from the feature dictionary PDF) ──────────────
graphology_dict = """
מילון הפיצ'רים הגרפולוגיים
הערות: חייב לרשום בעט כדורי! הניתוח מתייחס לכתב יד ימין.

1. נטיית הכתב (Slant)
נטיית הכתב חושפת את היחס של הכותב לסביבה ואת המזג שלו.
• נטייה שמאלה: מעידה על התנגדות, מופנמות, היצמדות לעבר ולעיתים מרדנות.
• נטייה ישרה ואנכית: משקף היגיון, שליטה עצמית, קור רוח וגישה רציונלית לחיים.
• נטייה ימינה: מצביעה על מוחצנות, ספונטניות, רגשנות וצורך עז להתקדם לעבר העתיד.

2. עובי קו (Stroke Thickness)
עובי הקו מייצג את "לחץ הכתיבה", שמעיד על כמות האנרגיה והיצרים של הכותב.
• קו דקיק ועדין: מעיד על רגישות גבוהה, רוחניות, עדינות, ולעיתים חוסר באנרגיה פיזית.
• קו בינוני ותקני: משקף חיוניות מאוזנת ובריאה.
• קו עבה ובצקי: מצביע על יצריות חזקה, נהנתנות, חומריות ואנרגיה פיזית מתפרצת.

3. היצמדות לשורה (Baseline Alignment) – אזורי כתיבה
האופן שבו הכותב ממקם את האותיות ביחס לשורה משקף את רמת היציבות והחיבור שלו למציאות.
• חותך את השורה כלפי מטה – אזור תחתון: מעיד על עייפות, כבדות, גישה פסימית או חיבור חזק לחומר ולקרקע.
• יושב במדויק על השורה – אזור אמצע: מצביע על יציבות רגשית, משמעת וראייה ריאליסטית.
• מרחף מעל השורה – אזור עליון: משקף אופטימיות, רוחניות, דמיון מפותח ולעיתים ניתוק מסוים מהמציאות.

4. מרווח בין מילים (Word Spacing)
משקף את המרחק החברתי שהכותב לוקח מהסביבה.
• צפוף ודבוק: מצביע על צורך עז בקרבה, חוסר יכולת להציב גבולות ותלות חברתית.
• מרווח תקני – גודל של 2 אותיות: מעיד על תקשורת בריאה ומרחק חברתי מאוזן.
• מרווח עצום: משקף צורך עצום בעצמאות, בדידות, ריחוק רגשי או רצון להתנתק מהסביבה.

5. שולי ימין – שולי פתיחה (Right Margin)
מייצגים את היחס לעבר, למשפחה ולנקודת המוצא.
• חוסר שוליים (צמוד לימין): מעיד על היצמדות לעבר, קושי לשחרר, חסכנות ותלות במשפחה.
• שוליים תקניים – 2 ס"מ: משקפים סדר, פרקטיות ואיזון בין העבר להווה.
• שוליים רחבים מאוד: מצביעים על רצון לברוח מהעבר, ניתוק מהשורשים וצורך בעצמאות.

6. שולי שמאל – שולי סיום (Left Margin)
מייצגים את היחס לעתיד, לחברה וללא נודע.
• חוסר שוליים (צמוד לשמאל): מעיד על ריצה אימפולסיבית קדימה, חוסר מעצורים וצורך עז בחברה.
• שוליים תקניים – 2 ס"מ: משקפים כיבוד גבולות, משמעת עצמית והסתגלות חברתית תקינה.
• שוליים רחבים מאוד: מצביעים על רתיעה מהעתיד, ביישנות, פחד מכישלון והימנעות מסיטואציות חדשות.

7. גודל הכתב האבסולוטי (Letter Size)
מלמד על תחושת הערך העצמי ועל המקום שהכותב רוצה לתפוס בעולם.
• כתב זעיר: מעיד על ריכוז פנומנלי, ירידה לפרטים, מופנמות, צניעות או חוסר ביטחון.
• כתב בינוני – רוחב 3 מ"מ לאות: משקף אגו מאוזן והסתגלות בריאה למציאות.
• כתב ענק: מצביע על מוחצנות, שאפתנות, צורך בתשומת לב ותחושת חשיבות עצמית.

8. מעגליות מול זוויתיות (Roundness vs. Angularity)
הצורה הגיאומטרית חושפת את מידת הרכות או הנוקשות של הכותב.
• כתב זוויתי וחד: מעיד על חשיבה אנליטית, תוקפנות, עקשנות, נחישות וביקורתיות.
• כתב תקני: משקף גמישות מחשבתית ויכולת להתאים את התגובה לסיטואציה.
• כתב עגול: מצביע על רכות, פשרנות, רגשנות, חברותיות ולעיתים קושי בהצבת גבולות.

9. שיפוע קו הבסיס (Baseline Slope)
הכיוון הכללי של השורה חושף את רמת האנרגיה ומצב הרוח של הכותב.
• שורה יורדת: מעידה על פסימיות, אכזבה, עייפות וחוסר אנרגיה לסיים משימות.
• שורה ישרה ושטוחה: משקפת יציבות רגשית, קור רוח, ראייה ריאליסטית והתמדה.
• שורה עולה: מצביעה על אופטימיות, שאפתנות, התלהבות ואנרגיה מתפרצת.

10. יחס רוחב-גובה של המילים (Word Aspect Ratio)
בודק עד כמה המילה נמתחת במרחב או מתכווצת לתוך עצמה.
• מילים צרות ומכווצות: מעידות על מופנמות, מעצורים רגשיים, ביישנות, חסכנות וזהירות.
• יחס פרופורציונלי – 1:1: משקף התנהלות חברתית תקינה, זרימה טבעית וחופש פעולה.
• מילים רחבות ומתוחות: מצביעות על מוחצנות, נדיבות, צורך עז במרחב מחיה וספונטניות.
"""

# ── 3. Call Claude Opus and get the report ──────────────────────────────────
client = anthropic.Anthropic(api_key=_api_key)

system_prompt = """אתה גרפולוג ותיק ומנוסה, שכתב דוחות אישיים לאלפי אנשים לאורך עשרות שנות עבודה.
הסגנון שלך: פסיכולוגי, חם, ישיר ובטוח בעצמו – כמו אדם שראה הרבה כתבי יד ויודע בדיוק מה הם אומרים.

כללים שאסור לשבור:
- כתוב עברית טבעית, ספרותית וזורמת – לא כאילו תורגמה ממחשב
- אל תכלול ביטויים כמו "מן הנתונים עולה", "על סמך הניתוח", "ניכר כי" – אלה ביטויי מחשב
- אל תשתמש בתבניות כגון "מצד אחד... מצד שני", "לסיכום", "ניתן לראות"
- אל תרשום רשימות תבליטים – רק פסקאות נרטיביות
- כתוב בגוף שלישי: "הכותב" / "הכותבת" (בחר אחד ועקוב בעקביות)
- אל תציג את עצמך ואל תוסיף הקדמות – פתח ישר בתיאור האדם
- הביטחון העצמי שלך כגרפולוג בא לידי ביטוי בטענות ישירות, לא בהסתייגויות
"""

user_prompt = f"""להלן נתוני כתב יד מנורמלים לסקלה 0–1:

{features_text}

מילון הפירושים הגרפולוגי:
{graphology_dict}

כתוב דוח גרפולוגי אישי על הכותב. אורך: 500–800 מילים. 
בסוף הדוח, הוסף משפט הסתייגות קצר שהניתוח מבוסס על כתב יד ימין."""

response = client.messages.create(
    model="claude-opus-4-5",
    max_tokens=2048,
    system=system_prompt,
    messages=[{"role": "user", "content": user_prompt}]
)

report = response.content[0].text
print(report)

הכותב נושא בתוכו מתח מעניין בין הרצון להתקרב לבין הצורך לשמור על עצמו. זהו אדם שפועל מתוך שכל ולא מתוך רגש גולמי, אך בשום אופן לא מדובר בקור – אלא בשליטה מודעת, בבחירה להגיב ולא רק להתפרץ.

כתב היד שלו מגלה אדם שיודע בדיוק כמה מעצמו הוא מוכן לתת. המרווחים הצפופים בין המילים מספרים על מישהו שזקוק לקרבה, לנוכחות של אחרים, לתחושה שהוא לא לבד במרחב. יש כאן משהו כמעט דוחק – כאילו השתיקה בין מילה למילה מרגישה לו לא נעימה, ולכן הוא ממהר למלא אותה. זהו אדם שמתקשה לשבת לבד בחדר זמן רב מדי, שמחפש שיח, עניין, גירוי אנושי. אבל הקרבה הזו היא לא תמימה – היא מחושבת. הוא מתקרב, אבל לא מתמסר.

את הזהירות הזו אפשר לראות בשוליים. מצד ימין, הוא כמעט נדבק לקצה הדף – כאילו לא מסוגל להיפרד מנקודת המוצא, מהמקום המוכר, מהשורשים. יש כאן אדם שהעבר תופס אצלו מקום של כבוד, אולי אפילו יותר מדי. הוא לא מאלה שמנתקים בקלות. החלטות ישנות, מערכות יחסים מהעבר, דפוסים שנבנו בילדות – כל אלה ממשיכים ללוות אותו, לפעמים ככוח מייצב ולפעמים כעוגן שמונע תנועה חופשית. מנגד, בשוליים השמאליים יש היסוס קל מהתקנה – הוא לא ממהר לקראת העתיד אלא ניגש אליו בצעדים מדודים, בודק את הקרקע לפני שהוא דורך.

גודל הכתב שלו נוטה מעט כלפי מעלה – לא ענקי ושתלטני, אך בהחלט נוכח. זהו אדם שיודע שיש לו מה להגיד, שמרגיש שהקול שלו צריך להישמע. הוא לא מאלה שמתכווצים בפינה, אבל גם לא מאלה שדורשים את כל הבמה. יש לו ביטחון, אבל הביטחון הזה שקט – הוא לא צריך להוכיח לאף אחד כלום, אך גם לא מוותר על המקום שמגיע לו.

הנטייה הקלה של האותיות ימינה מעידה על פתיחות מסוימת, על נכונות ללכת קדימה, להיפגש עם העולם. הוא לא נסוג אחורה ולא מתבצר בתוך עצמו, אך גם לא נופל על הצוואר של כל מי שפוגש. זו גישה בוגרת – של מי שמבין שקשרים נבנים בהדרגה, לא בסערה.

המילים עצמן כתובות בצורה צרה, מכווצת, כאילו כל מילה מחזיקה את עצמה הדוק. יש כאן מופנמות שלא רואים במבט ראשון. כלפי חוץ הוא אולי נראה פתוח ונגיש, אבל בפנים קיימים מעצורים. הוא חושב הרבה לפני שמדבר, שוקל מילים, בודק איך הן יתקבלו. יש לו עולם פנימי עשיר שהוא לא ממהר לחשוף. אנשים כאלה לפעמים מפתיעים את סביבתם – דווקא כשחושבים שמכירים אותם, מתגלה שכבה נוספת, עמוקה יותר, שנשמרה בקפידה.

הלחץ העדין על הנייר מחזק את התמונה הזו. אין כאן כוחניות, אין התפרצות של אנרגיה גולמית. הוא פועל בעדינות, מעדיף שכנוע על כפייה, מילה נכונה על צעקה. יש בו רגישות שלפעמים עלולה להפוך לחולשה – הוא קולט יותר מדי, מרגיש דברים שאחרים לא שמים לב אליהם, ולעיתים זה מתיש.

העגלגלות הקלה באותיות מוסיפה נופך של רכות, של יכולת להכיל, לסלוח, להבין. הוא לא נוקשה ולא דוגמטי. כשצריך, הוא יודע להתגמש, לוותר על עמדה, למצוא פשרה. זה לא חולשה – זו חוכמה של מי שמבין שהחיים לא מתנהלים בקווים ישרים.

קו הבסיס שלו יציב, עם נטייה עדינה כלפי מעלה – אופטימיות זהירה, אמונה שהדברים יסתדרו, אבל לא תמימות. הוא לא מאמין בניסים, הוא מאמין בעבודה. מצב הרוח שלו יציב, לא נתון לתנודות דרמטיות, ויש לו יכולת להמשיך גם כשקשה.

בסיכומו של דבר, עומד לפנינו אדם מורכב שמנווט בין צרכים סותרים – בין הרצון בקרבה לבין הצורך בהגנה, בין הנאמנות לעבר לבין השאיפה לצמוח, בין הרגישות הפנימית לבין ההופעה המאוזנת כלפי חוץ. הוא לא קורא את עצמו בקול רם, ומי שרוצה להכיר אותו באמת יצטרך להתאזר בסבלנות. אבל למ